### ISSUE TITLE
Add support for pandoc loader

### ISSUE THREAD

**Issue by prabirshrestha** [Abraxas-365/langchain-rust#100]
[pandoc](https://pandoc.org) supports lot of file formats. We should create a `PandocLoader`. Because files can be large we want to use `AsyncRead`. We probably want to convert all `Reader` to `AsyncReader` in the code that is already in the main branch.

For the python library, the seem to instead have [EpubLoader](https://python.langchain.com/docs/integrations/document_loaders/epub) which internally uses `pandoc`. We might still want to create `PandocLoader` so we don't have to reimplement tons of loader.

**Comment by Abraxas-365** [comment]
add pandoc loader #104
