### ISSUE TITLE
Add support for local embedding models

### ISSUE THREAD

**Issue by prabirshrestha** [Abraxas-365/langchain-rust#106]
When you have large number of documents you want to create embedding, you may easily hit rate limits. To over come this we should have support for local embedding. While we can currently do this with ollama, we need to have an ollama server running.

Having local embeddings such as [fastembed-rs](https://github.com/Anush008/fastembed-rs) would allow us to easily create desktop/cli apps.

**Comment by Abraxas-365** [comment]
https://github.com/Abraxas-365/langchain-rust/pull/108
