### ISSUE TITLE
Support ConversationalRetrievalChain

### ISSUE THREAD

**Issue by timvw** [Abraxas-365/langchain-rust#115]
**Is your feature request related to a problem? Please describe.**
Add ConversationalRetrievalChain

**Describe the solution you'd like**
A chain that implements the [ConversationalRetrievalChain](https://api.python.langchain.com/en/latest/_modules/langchain/chains/conversational_retrieval/base.html#ConversationalRetrievalChain_)

**Describe alternatives you've considered**
We could not implement it.

**Additional context**
In order to implement a chatbot this chain is the most suitable.

**Comment by Abraxas-365** [comment]
Hi @timvw  I will implement it. It's a mix of the retriever with the conversational chain. Give me a day or two.🚀

**Comment by Abraxas-365** [comment]
#116

**Comment by Abraxas-365** [comment]
Hi its finished, 
https://github.com/Abraxas-365/langchain-rust/blob/main/examples/conversational_retriver_simple_chain.rs

https://github.com/Abraxas-365/langchain-rust/blob/main/examples/conversational_retriver_chain_with_vector_store.rs
