### ISSUE TITLE
Document Loader Filters

### ISSUE THREAD

**Issue by aliumujib** [Abraxas-365/langchain-rust#203]
**Is your feature request related to a problem? Please describe.**

I need to filter files and paths using regex patterns that users of my app will specify. As at v.4.30 `langchain-rust` useful features for file filtering via `DirLoaderOptions` but lacks built-in support for regex-based filtering for files and directories. This limitation makes it cumbersome to exclude or include files based on more complex patterns.

**Describe the solution you'd like**

I propose integrating regex-based filtering into the library. This feature would allow users to specify regex patterns for including or excluding files and directories when processing paths. The integration could involve adding functionality that allows users to provide regex patterns in configuration options, and then use those patterns to filter files during processing.

**Describe alternatives you've considered**

An alternative approach could be to provide a more general filtering mechanism, such as supporting glob patterns or simple substring matching. However, regex offers greater flexibility and power for complex matching scenarios, which would be beneficial for users with more advanced filtering needs.

**Additional context**

I would be happy to contribute to this enhancement by submitting a Pull Request (PR) if this feature aligns with the project's goals. Please let me know if you would be open to this contribution or if you have any suggestions on how to proceed.

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/Abraxas-365/langchain-rust/pull/204
