### ISSUE TITLE
Integrate llama.cpp as an Inference Server

### ISSUE THREAD

**Issue by rizgan** [Abraxas-365/langchain-rust#234]
## Overview
We need to add support for using [llama.cpp](https://github.com/ggerganov/llama.cpp) as an inference server in our project. llama.cpp is known for its speed, cross-platform compatibility, and support for a wide range of embedding and LLM models.

## Feature Description
Implement functionality to integrate llama.cpp as an inference server option in our project. This integration should leverage llama.cpp's advantages, including:

1. Fast inference speed
2. Cross-platform compatibility
3. Support for a wide variety of embedding and LLM models

### 1. llama.cpp Integration
- Implement a method to use llama.cpp as a backend for inference tasks
- Allow users to specify llama.cpp as the inference engine of choice

### 2. Model Support
- Enable loading and using various models supported by llama.cpp
- Implement a system to manage and switch between different models

### 3. Inference Tasks
- Support both embedding generation and text generation tasks
- Implement appropriate interfaces for different types of inference tasks

### 4. Performance Optimization
- Utilize llama.cpp's speed advantages to improve overall system performance
- Implement batching and caching mechanisms if applicable

### 5. Cross-Platform Support
- Ensure the integration works across different platforms (Windows, Linux, macOS)
- Provide clear instructions for setup on various operating systems

## Technical Requirements
1. Implement a wrapper or interface to interact with llama.cpp
2. Develop a model management system compatible with llama.cpp's model format
3. Create APIs for embedding generation and text generation tasks
4. Implement error handling and logging for the llama.cpp integration
5. Ensure proper resource management (memory, GPU utilization if applicable)

## Acceptance Criteria
- [ ] llama.cpp can be successfully integrated and used as an inference server
- [ ] Users can specify llama.cpp as the inference engine through configuration or CLI
- [ ] The system can load and use various models supported by llama.cpp
- [ ] Embedding generation tasks can be performed using llama.cpp
- [ ] Text generation tasks can be performed using llama.cpp
- [ ] The integration demonstrates improved performance compared to current solutions
- [ ] The integration works on Windows, Linux, and macOS
- [ ] Comprehensive documentation is provided for setup and usage

## Additional Considerations
- Investigate the possibility of using llama.cpp's quantization features for model optimization
- Consider implementing a benchmark system to compare performance with other inference solutions
- Explore options for fine-tuning or adapting models within the llama.cpp ecosystem
- Keep track of llama.cpp updates and ensure our integration can be easily updated

## Resources
- llama.cpp GitHub repository: https://github.com/ggerganov/llama.cpp
- Documentation on supported models and setup instructions should be referenced during implementation

**Comment by prabirshrestha** [comment]
llama.cpp already has open ai compatible server which you can use. https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md

You can set custom api base as shown here. https://github.com/Abraxas-365/langchain-rust/blob/80f61b684e4a91b4c53d273a52db35da20325174/examples/llm_openai.rs#L12C1-L18C1

Would this work for you or are you suggesting us to embed llama.cpp? I'm not a fan of embedding llama.cpp in langchain-rust as this will increase the overhead for us due to the fact that llama.cpp updates at a very fast speed and we will be in catchup mode all the time. I follow few repos and I keep seeing lot of issues related to can it support model X and would like to avoid it.

**Comment by rizgan** [comment]
Can you please add to you example folder this llama.cpp example. I spent a little bit time to find out the correct endpoint for llama.cpp.

1. Run llama.cpp: `.\llama.exe --port 8181 -m models\<YOUR-MODEL-NAME>.gguf --threads 8 -ngl 100 -c 4096 --n-gpu-layers 99 --api-key <YOUR-API-KEY>`
2. Use this code:
```
use langchain_rust::llm::OpenAIConfig;
use langchain_rust::{language_models::llm::LLM, llm::openai::OpenAI};

#[tokio::main]
async fn main() {
    let open_ai = OpenAI::default().with_config(
        OpenAIConfig::default()
            .with_api_base("http://localhost:8181/v1")
            .with_api_key("<YOUR-API-KEY>"), // Uncomment if you need to set your OpenAI key
    );
    
    let prompt = "Building a website can be done in 10 simple steps:";
    
    match open_ai.invoke(prompt).await {
        Ok(response) => println!("{}", response),
        Err(e) => eprintln!("Error: {:?}", e),
    }
}
```
Thanks for you help, @prabirshrestha!

Is there is way to also use custom API for embedding models? I would like also use llama.cpp as embedding server.

**Comment by rizgan** [comment]
And here example of using llama.cpp as embedding server:

```
use langchain_rust::embedding::embedder_trait::Embedder;
use langchain_rust::embedding::openai::openai_embedder::OpenAiEmbedder;
use langchain_rust::llm::OpenAIConfig;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config = OpenAIConfig::default()
        .with_api_base("http://localhost:8282/v1".to_string())
        .with_api_key("a684e734-f8b4-4967-8723-4ac393638338".to_string()); // llama.cpp doesn't require an API key

    let embedder = OpenAiEmbedder::new(config);

    let text = "Why is the sky blue?";
    let embedding = embedder.embed_query(text).await?;

    println!("Embedding for '{}': {:?}", text, embedding);

    Ok(())
}
```
