### ISSUE TITLE
Add more LLMs integrations

### ISSUE THREAD

**Issue by Abraxas-365** [Abraxas-365/langchain-rust#5]
# Description
At the current date, the only available integration for OpenAI's Large Language Model (LLM) is with ChatGPT. However, it would be highly beneficial to expand this integration to other platforms such as Azure or OLLAMA. This expansion would allow users to leverage the capabilities of LLM in a wider range of applications and environments, enhancing flexibility and accessibility.

# Proposed Solution
Integrate OpenAI's LLM with Azure and/or OLLAMA to enable users to utilize the model within these platforms seamlessly. This integration could involve developing APIs, SDKs, or plugins that facilitate easy integration and interaction with LLM.

# Expected Benefits
- Enhanced Accessibility: Users will have the flexibility to access LLM through multiple platforms, catering to diverse needs and preferences.
- Improved Workflow Integration: Integration with Azure and OLLAMA will streamline workflows for developers and researchers, allowing them to leverage LLM within their existing environments.
- Expanded User Base: By integrating with popular platforms like Azure and OLLAMA, OpenAI can reach a broader audience, fostering greater adoption and utilization of LLM.

# Community Feedback
Please share your thoughts and feedback on this proposed integration. Your input will help us prioritize and shape the development of this feature.

**Comment by prabirshrestha** [comment]
My suggestion is to allow setting `base_url` in `OpenAI` and make the make the model `Into<String>` as ollama supports [Open AI Compatibility](https://ollama.com/blog/openai-compatibility). `keep_alive` is another feature you probably want to add since ollama can use that to detect when to unload the model.

**Comment by Abraxas-365** [comment]
@prabirshrestha
## Some Options
- Maybe we can add the keep alive to the llmoption? *src/language_models/options.rs*.
- Crate another with_keep_alive in the self builder of opens ai 
- Copy the open ai implementation to another struct Ollama and add the keep alive in the self builder
 
What are your thoughts 😄

**Comment by prabirshrestha** [comment]
I don't have a strong opinion for now. Probably worth seeing what other open api compatibility APIs adds to such as https://edgen.co. I'm ok on waiting for this as I'm not in rush to use this feature. I'm also waiting for the embedding api to support compatibility and see where it makes sense.
