### ISSUE TITLE
Add OpenAI tools & function calling

### ISSUE THREAD

**Issue by prabirshrestha** [Abraxas-365/langchain-rust#74]
Ref: 
* https://platform.openai.com/docs/assistants/tools
* https://python.langchain.com/docs/modules/agents/agent_types/openai_tools
* https://python.langchain.com/docs/modules/model_io/chat/function_calling

There are bunch of models that now support tools and function calling. This would allow us to have a json schema defined and force the model to return a json response allowing us to easily use this to add new capabilities.

```js
assistant = client.beta.assistants.create(
  instructions="You are a weather bot. Use the provided functions to answer questions.",
  model="gpt-4-turbo-preview",
  tools=[{
      "type": "function",
    "function": {
      "name": "getCurrentWeather",
      "description": "Get the weather in location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {"type": "string", "description": "The city and state e.g. San Francisco, CA"},
          "unit": {"type": "string", "enum": ["c", "f"]}
        },
        "required": ["location"]
      }
    }
  }, {
    "type": "function",
    "function": {
      "name": "getNickname",
      "description": "Get the nickname of a city",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {"type": "string", "description": "The city and state e.g. San Francisco, CA"},
        },
        "required": ["location"]
      }
    } 
  }]
)
```

**Comment by Abraxas-365** [comment]
https://python.langchain.com/docs/modules/agents/agent_types/

Langchain python have an specific type called [OpenAI Tools](https://python.langchain.com/docs/modules/agents/agent_types/openai_tools) and [OpenAI Functions](https://python.langchain.com/docs/modules/agents/agent_types/openai_functions_agent). should do the same? using the same names? or should we try to use other naming aproach?

**Comment by stefonalfaro** [comment]
Function calling seems to have been defined here but the response is not returning anything. You can set it up like
`    let mut functions = Vec::new();

    functions.push(FunctionDefinition {
        name: "cli".to_string(),
        description: "Use the Ubuntu command line to preform any action you wish.".to_string(),
        parameters: json!({
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "The raw command you want executed"
                }
            },
            "required": ["command"]
        })
    });
    
    let llm = OpenAI::default()
    .with_model(OpenAIModel::Gpt4Turbo)
    .with_config(
        OpenAIConfig::new()
            .with_api_key("sk-key")
    )
    .with_options(
        CallOptions::new()
            .with_functions(functions)
    );`

but the problem is when you call it you get an empty response. You will only get the empty response when adding the CallOption Functions. Regular execution without functions will work.
`    let response = llm.invoke("Use the command line to create a new rust project. Execute the first command.").await.unwrap();
    dbg!(&response);
    println!("{}", response)`

**Comment by prabirshrestha** [comment]
@Abraxas-365 Different models can have different way to defining function calling. Though most models now seem to be going with open ai style function calling.

https://ollama.com/library/nexusraven
https://github.com/MeetKai/functionary
https://huggingface.co/cfahlgren1/natural-functions

**Comment by Abraxas-365** [comment]
> Function calling seems to have been defined here but the response is not returning anything. You can set it up like
> 
> ```
> let mut functions = Vec::new();
> 
> functions.push(FunctionDefinition {
>     name: "cli".to_string(),
>     description: "Use the Ubuntu command line to preform any action you wish.".to_string(),
>     parameters: json!({
>         "type": "object",
>         "properties": {
>             "command": {
>                 "type": "string",
>                 "description": "The raw command you want executed"
>             }
>         },
>         "required": ["command"]
>     })
> });
> 
> let llm = OpenAI::default()
> .with_model(OpenAIModel::Gpt4Turbo)
> .with_config(
>     OpenAIConfig::new()
>         .with_api_key("sk-key")
> )
> .with_options(
>     CallOptions::new()
>         .with_functions(functions)
> );
> ```
> 
> but the problem is when you call it you get an empty response. You will only get the empty response when adding the CallOption Functions. Regular execution without functions will work.
> 
> ```
> let response = llm.invoke("Use the command line to create a new rust project. Execute the first command.").await.unwrap();
>     dbg!(&response);
>     println!("{}", response)
> ```


Yes, we have the option to use functions, but as of today, we haven't implemented a way to return the function's output. I think it will be quite simple if we return the output as JSON stringified. and parse it on the output

**Comment by Abraxas-365** [comment]
> @Abraxas-365 Different models can have different way to defining function calling. Though most models now seem to be going with open ai style function calling.
> 
> 
> 
> https://ollama.com/library/nexusraven
> 
> https://github.com/MeetKai/functionary
> 
> https://huggingface.co/cfahlgren1/natural-functions
> 
> 
> 
> 

I think we can create an output parser which extracts the sting convert it as a open ai function output and extract the infomation

**Comment by Abraxas-365** [comment]
https://github.com/Abraxas-365/langchain-rust/pull/76

@stefonalfaro @prabirshrestha With this PR, we can get the function call as output.

**Comment by Abraxas-365** [comment]
Solved in https://github.com/Abraxas-365/langchain-rust/pull/76
